#!/bin/bash

if [ "$#" -ne 1 ] ; then
        echo "$0 <device>" >&2
        exit 1
else
        if echo "$1"|grep -qE 'xvd[a-z][0-9]?' ; then
                echo "$1" | sed -e 's/xvd/sd/'
    elif echo "$1"|grep -qE 'vd[a-z][0-9]?' ; then
        echo "$1" | sed -e 's/vd/sd/'
        else
                echo "$1"
        fi
fi
