#!/bin/bash
# A simple bash script that runs regular statistics on the wiki page.

STATSFILE="Wiki-Statistics.md"
GITPATH="./eucalyptus.wiki/"

cd ${GITPATH}

# Note: first echo rewrites (>) the file, subsequent cats append (>>) to the file.
echo "# Wiki Statistics">${STATSFILE}
echo "## Last 25 Commits" >> $STATSFILE
echo "<pre>" >> $STATSFILE
git log -n 25 --pretty="%cn, %s (%h), %cr" >> $STATSFILE
echo "</pre>" >> $STATSFILE

echo "## Most Active Contributors, Last Month:" >> $STATSFILE
echo "<pre>" >> $STATSFILE
git log --since @{"1 month"} --pretty="%cn" | sort | uniq -c | sort -r >> $STATSFILE
echo "</pre>" >> $STATSFILE

echo "## Most Active Contributors, All Time:" >> $STATSFILE
echo "<pre>" >> $STATSFILE
git log --pretty="%cn" | sort | uniq -c | sort -r >> $STATSFILE
echo "</pre>" >> $STATSFILE

echo "*****" >> $STATSFILE
echo "[[category.stats]]" >> $STATSFILE
echo "WARNING: This file is automatically generated. Changes will be overwritten." >> $STATSFILE
